### ISSUE TITLE
Python script downloads a file with 22kb

### ISSUE THREAD

**Issue by therealcodemonger** [aman-roy/mp3_downloader#5]
The site is working perfectly, no problem with that however just tried the script and seems like it didn't do that magic.. :( 

This is what I got: 
````
Created by Aman Roy
    FB:- amanroy007
    Email:- royaman8757@gmail.com
                         Select A mode
    [1] Download from a list
    [2] Download from direct entry
    Press any other key from keyboard to exit
>>> 2
Enter the song name or youtube link: https://www.youtube.com/watch?v=SbUBMklQSVU

Downloading Sean Paul - She Doesn&#39;t Mind [Official Music Video] - YouTube

Exiting....

Have a good day.
```

See the below screenshot -
![image](https://cloud.githubusercontent.com/assets/17482144/22020150/c000705a-dcdc-11e6-8e90-47cd5eb4da4c.png)

Hope we can get this fixed or working :smiley: soon

**Comment by PossiblyKozak** [comment]
I've forked this project and been improving it in ways like this. When that happened to me, that was typically because the song was either blocked, or the program downloads the HTML of the website. Annoying, I know. 

Come take a look at what I've done, https://github.com/PossiblyKozak/mp3_downloader

**Comment by aman-roy** [comment]
@grohit19 Issue has been resolved. Check it.
